networks:
  laravel_network:

services:
  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: laravel_restaurante_server
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - laravel_network

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: laravel_restaurante_php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel_network
    healthcheck:
      test: ["CMD", "php", "-r", "echo 'OK';"]
      interval: 5s
      timeout: 2s
      retries: 10

  mysql:
    image: mysql:8.0.1
    container_name: laravel_restaurante_mysql
    restart: unless-stopped
    env_file:
      - mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: laravel_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root.pa55
    networks:
      - laravel_network

  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel_network

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - laravel_network

  node:
    image: node:22
    working_dir: /var/www/html
    command: bash
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_network
